# Generated by Django 5.1.1 on 2024-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_chatmessage_options_alter_session_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="agent",
            field=models.CharField(
                choices=[("simple_agent", "Simple Agent")],
                default="simple_agent",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="engine",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("mlx", "Apple MLX"),
                    ("hf", "HuggingFace"),
                    ("premai", "PremAI"),
                ],
                default="openai",
                max_length=255,
            ),
        ),
    ]
