# Generated by Django 5.1.1 on 2024-09-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("llm", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "db_type",
                    models.CharField(
                        choices=[("postgres", "PostgreSQL"), ("sqlite", "SQLite")],
                        default="sqlite",
                        max_length=255,
                    ),
                ),
                (
                    "db_connection_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("sql", models.TextField(blank=True, null=True)),
                ("llm", models.CharField(blank=True, max_length=255, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_new_tokens", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("include", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_filters",
                        to="chat.session",
                    ),
                ),
            ],
        ),
    ]
