# Generated by Django 5.1.1 on 2024-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="db_type",
            field=models.CharField(
                choices=[("PostgreSQL", "postgres"), ("SQLite", "sqlite")],
                default="sqlite",
                max_length=255,
            ),
        ),
    ]
