# Generated by Django 5.1.1 on 2024-10-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="sql",
            new_name="additional_knowledge",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="table",
            new_name="dataframe",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="response",
            new_name="sql_string",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="chat_id",
            new_name="session_id",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="name",
            new_name="session_name",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="llm",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="max_new_tokens",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="session",
            name="llm",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="bot_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="few_shot_examples",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="plot_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="engine",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("other_engine", "Other Engine")],
                default="openai",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="exclude",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="session",
            name="include",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="session",
            name="max_new_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="model_name",
            field=models.CharField(
                blank=True, default="gpt-4o", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TableFilter",
        ),
    ]
