# Generated by Django 5.1.1 on 2024-10-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_session_agent_alter_session_engine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="session",
            name="engine",
        ),
        migrations.RemoveField(
            model_name="session",
            name="max_new_tokens",
        ),
        migrations.RemoveField(
            model_name="session",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="session",
            name="temperature",
        ),
        migrations.AddField(
            model_name="session",
            name="agent_name",
            field=models.CharField(default="simple_agent", max_length=255),
        ),
        migrations.AddField(
            model_name="session",
            name="config_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="env_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
