# Generated by Django 5.1.1 on 2024-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_session_agent_remove_session_engine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="db_type",
            field=models.CharField(
                choices=[("postgres", "PostgreSQL"), ("sqlite", "SQLite")],
                default="sqlite",
                max_length=255,
            ),
        ),
    ]
