# Generated by Django 5.1.1 on 2024-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_chatmessage_plot_dataframe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="id",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_id",
            field=models.AutoField(default=10000000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
