# Generated by Django 5.1.2 on 2024-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_db_path",
            field=models.CharField(max_length=255),
        ),
    ]
